name: Deploy Strapi App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Only installs dependencies locally if needed for build (optional)
      - name: Install Dependencies
        run: npm ci

      - name: Build Admin Panel
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.DO_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload Project to Server
        run: |
          rsync -avz --delete \
            --exclude="node_modules" \
            --exclude=".cache" \
            --exclude=".env" \
            --exclude="build" \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/home/deployer/smart-coded-strapi-fyonka/

      - name: Install & Restart on Server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            cd /home/deployer/smart-coded-strapi-fyonka
            
            # Check Node.js version
            node_version=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
            if [ "$node_version" -lt 18 ]; then
              echo "❌ Node.js version $node_version is not supported. Strapi 5.x requires Node.js ≥18"
              exit 1
            fi
            
            # Set environment variables
            export NODE_ENV=production
            
            # Clean install dependencies
            rm -rf node_modules package-lock.json
            npm install --production --no-audit
            
            # Build the application
            npm run build
            
            # Restart PM2
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
            
            # Save PM2 configuration
            pm2 save
          EOF

      - name: Reload Nginx (optional)
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
            "sudo nginx -t && sudo systemctl reload nginx"