name: Deploy Strapi App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Admin Panel
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.DO_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload Project to Server
        run: |
          rsync -avz --delete \
            --exclude="node_modules" \
            --exclude=".cache" \
            --exclude=".env" \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="*.log" \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/home/deployer/smart-coded-strapi-fyonka/

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            cd /home/deployer/smart-coded-strapi-fyonka
            
            # Set direct paths
            export NODE_PATH="/root/.nvm/versions/node/v18.20.8/bin/node"
            export NPM_PATH="/root/.nvm/versions/node/v18.20.8/bin/npm"
            export PM2_PATH="/root/.nvm/versions/node/v18.20.8/bin/pm2"
            export PM2_DIRECT="/root/.nvm/versions/node/v18.20.8/lib/node_modules/pm2/bin/pm2"
            
            # Fix permissions
            chmod +x "$PM2_PATH" 2>/dev/null || true
            chmod +x "$PM2_DIRECT" 2>/dev/null || true
            chmod +x /root/.nvm/versions/node/v18.20.8/bin/* 2>/dev/null || true
            
            echo "Environment check:"
            echo "Node: $($NODE_PATH --version)"
            echo "NPM: $($NPM_PATH --version)"
            
            # Try PM2, fallback to direct execution
            if [ -x "$PM2_PATH" ]; then
              echo "PM2 via symlink: $($PM2_PATH --version)"
              PM2_CMD="$PM2_PATH"
            elif [ -x "$PM2_DIRECT" ]; then
              echo "PM2 via direct path: $($NODE_PATH $PM2_DIRECT --version)"
              PM2_CMD="$NODE_PATH $PM2_DIRECT"
            else
              echo "❌ PM2 not executable, trying alternative approach"
              # Try using /usr/local/bin/pm2 symlink
              if [ -L /usr/local/bin/pm2 ]; then
                chmod +x /usr/local/bin/pm2 2>/dev/null || true
                PM2_CMD="/usr/local/bin/pm2"
                echo "Using system PM2: $(/usr/local/bin/pm2 --version)"
              else
                echo "❌ No working PM2 found"
                exit 1
              fi
            fi
            
            # Install production dependencies
            export NODE_ENV=production
            $NPM_PATH install --production --no-audit --no-fund
            
            # Create ecosystem config
            cat > ecosystem.config.js <<'PMCONFIG'
          module.exports = {
            apps: [{
              name: 'strapi-app',
              script: './node_modules/.bin/strapi',
              args: 'start',
              cwd: '/home/deployer/smart-coded-strapi-fyonka',
              env: {
                NODE_ENV: 'production',
                PORT: 1337,
                HOST: '0.0.0.0'
              },
              instances: 1,
              exec_mode: 'fork',
              watch: false,
              max_memory_restart: '1G',
              error_file: './logs/err.log',
              out_file: './logs/out.log',
              log_file: './logs/combined.log',
              time: true
            }]
          };
          PMCONFIG
            
            # Create logs directory
            mkdir -p logs
            chown -R deployer:deployer /home/deployer/smart-coded-strapi-fyonka || true
            
            # Stop and delete existing app
            $PM2_CMD stop strapi-app 2>/dev/null || true
            $PM2_CMD delete strapi-app 2>/dev/null || true
            
            # Start the application
            $PM2_CMD start ecosystem.config.js
            $PM2_CMD save
            $PM2_CMD list
            
            echo "✅ Deployment completed successfully!"
          EOF

      - name: Health Check
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            # Find working PM2 command
            if [ -x "/root/.nvm/versions/node/v18.20.8/bin/pm2" ]; then
              PM2_CMD="/root/.nvm/versions/node/v18.20.8/bin/pm2"
            elif [ -x "/usr/local/bin/pm2" ]; then
              PM2_CMD="/usr/local/bin/pm2"
            elif [ -x "/root/.nvm/versions/node/v18.20.8/lib/node_modules/pm2/bin/pm2" ]; then
              PM2_CMD="/root/.nvm/versions/node/v18.20.8/bin/node /root/.nvm/versions/node/v18.20.8/lib/node_modules/pm2/bin/pm2"
            else
              echo "❌ No working PM2 found for health check"
              exit 1
            fi
            
            # Wait for startup
            sleep 15
            
            # Check PM2 status
            echo "PM2 Status:"
            $PM2_CMD list
            $PM2_CMD show strapi-app
            
            # Check if port 1337 is listening
            if ss -tlnp | grep -q ":1337"; then
              echo "✅ Application is listening on port 1337"
            else
              echo "❌ Application not listening on port 1337"
              echo "PM2 logs:"
              $PM2_CMD logs strapi-app --lines 30
              exit 1
            fi
          EOF