name: Deploy Strapi App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Admin Panel
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.DO_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload Project to Server
        run: |
          rsync -avz --delete \
            --exclude="node_modules" \
            --exclude=".cache" \
            --exclude=".env" \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="*.log" \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/home/deployer/smart-coded-strapi-fyonka/

      - name: Deploy and Restart Application
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            cd /home/deployer/smart-coded-strapi-fyonka
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            echo "Node.js version: $(node --version)"
            echo "NPM version: $(npm --version)"
            
            export NODE_ENV=production
            
            npm install --production --no-audit --no-fund
            
            if [ ! -f "ecosystem.config.js" ]; then
              cat > ecosystem.config.js <<'EOLCONFIG'
          module.exports = {
            apps: [{
              name: 'strapi-app',
              script: './node_modules/.bin/strapi',
              args: 'start',
              cwd: '/home/deployer/smart-coded-strapi-fyonka',
              env: {
                NODE_ENV: 'production',
                PORT: 1337,
                HOST: '0.0.0.0'
              },
              instances: 1,
              exec_mode: 'fork',
              watch: false,
              max_memory_restart: '1G',
              error_file: './logs/err.log',
              out_file: './logs/out.log',
              log_file: './logs/combined.log',
              time: true,
              min_uptime: '10s',
              max_restarts: 5
            }]
          };
          EOLCONFIG
            fi
            
            mkdir -p logs
            chown -R deployer:deployer /home/deployer/smart-coded-strapi-fyonka || true
            
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi
            
            pm2 stop strapi-app || true
            pm2 delete strapi-app || true
            pm2 start ecosystem.config.js
            pm2 save
            pm2 list
            
            echo "Deployment completed successfully!"
          EOF

      - name: Health Check
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            sleep 15
            
            if pm2 list | grep -q "strapi-app.*online"; then
              echo "Application is running in PM2"
            else
              echo "Application failed to start"
              pm2 logs strapi-app --lines 20
              exit 1
            fi
            
            if netstat -tlnp | grep -q ":1337"; then
              echo "Application is listening on port 1337"
            else
              echo "Application is not listening on port 1337"
              pm2 logs strapi-app --lines 20
              exit 1
            fi
          EOF

      - name: Reload Nginx
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} <<'EOF'
            if command -v nginx &> /dev/null; then
              if sudo nginx -t; then
                sudo systemctl reload nginx
                echo "Nginx reloaded successfully"
              else
                echo "Nginx configuration test failed"
              fi
            else
              echo "Nginx not installed, skipping reload"
            fi
          EOF